name: Node CI

on: 
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      name: Install dependencies
    - run: yarn lint
      name: Lint source code
    - run: yarn build
      name: Build code
    - run: yarn test
      name: Run unit tests
      env:
        CI: true
